"""Lazy public facade for the dynamic discretization discovery package."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS_BY_MODULE: dict[str, tuple[str, ...]] = {
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow': (
        'DddArcFlowResourceRowMode',
        'DddFixedKArcFlowOptimizer',
        'DddFixedKArcFlowProgress',
        'DddFixedKArcFlowResult',
        'DddFixedKArcFlowSolveConfig',
        'DddFixedKArcFlowStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_network': (
        'DddArcFlowResourceClique',
        'DddArcFlowBoundaryInterval',
        'DddArcFlowResourceInterval',
        'DddCabinTimeExpandedArc',
        'DddCabinTimeExpandedNetwork',
        'DddCabinTimeExpandedNetworkBuilder',
        'build_ddd_arc_flow_resource_cliques',
        'build_ddd_arc_flow_boundary_intervals',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_movement': (
        'DddFixedKMovementArcFlowConfig',
        'DddFixedKMovementArcFlowOptimizer',
        'DddFixedKMovementArcFlowProgress',
        'DddFixedKMovementArcFlowResult',
        'DddFixedKMovementArcFlowStatus',
        'DddMovementArcFlowObjectiveMode',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_movement_master': (
        'DddArcFlowMovementMaster',
        'DddArcFlowMovementMasterBuilder',
        'build_ddd_arc_flow_movement_values',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_passenger_domain': (
        'DddArcFlowPassengerCapacityRow',
        'DddArcFlowPassengerDemandRow',
        'DddArcFlowPassengerDomain',
        'DddArcFlowPassengerDomainBuilder',
        'DddArcFlowPassengerEqualityRow',
        'DddArcFlowPassengerFlow',
        'DddArcFlowPassengerVariable',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_passenger_model': (
        'DddArcFlowIntegratedPassengerModel',
        'DddArcFlowPassengerModelBuilder',
        'DddArcFlowPassengerRecourseModel',
        'DddArcFlowPassengerRecourseResult',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_preparation': (
        'DddArcFlowProblemPreparer',
        'DddPreparedArcFlowProblem',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.arc_flow_relaxation': (
        'DddArcFlowRelaxationConfig',
        'DddArcFlowRelaxationMethod',
        'DddArcFlowRelaxationOptimizer',
        'DddArcFlowRelaxationProgress',
        'DddArcFlowRelaxationResult',
        'DddArcFlowRelaxationStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.passenger_recourse': (
        'DddFixedMovementPassengerRecourseOracle',
        'DddPassengerLpIpComparison',
        'DddPassengerRecourseConfig',
        'DddPassengerRecourseResult',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.passenger_benders_cuts': (
        'DddPassengerBendersCut',
        'DddPassengerBendersCutPool',
        'build_ddd_passenger_benders_cut',
        'ddd_movement_vector_signature',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.passenger_benders_outer_loop': (
        'DddOuterLoopLpBendersConfig',
        'DddOuterLoopLpBendersIteration',
        'DddOuterLoopLpBendersProgress',
        'DddOuterLoopLpBendersResult',
        'DddOuterLoopLpBendersSolver',
        'DddOuterLoopLpBendersStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.aggregate_support': (
        'DddAggregateRouteCount',
        'DddAggregateRouteCountLiteral',
        'DddAggregateSupportCut',
        'DddAggregateSupportDistanceCut',
        'DddCpSatFixedSupport',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.artifact_adapter': (
        'EanArtifactToDddMovementProblemAdapter',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.balanced_reference_start': (
        'DddBalancedReferenceStartBuilder',
        'DddBalancedReferenceStartResult',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.cp_sat_primal': (
        'DddCpSatPassengerObjectiveEvent',
        'DddCpSatPassengerRidePreference',
        'DddCpSatPrimalOracle',
        'DddCpSatPrimalResult',
        'DddCpSatPrimalStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.cp_sat_round': (
        'DddCpSatMasterCoupling',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.ean_plan_adapter': (
        'DddReferenceToEanMovementPlanAdapter',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.fixed_k': (
        'DddFixedKExperimentProfile',
        'DddFixedKOperatingMode',
        'DddFixedKProfileConfig',
        'DddFixedKStartPolicy',
        'DddFixedKBoundaryContext',
        'DddFixedKTrajectoryProblem',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.fixed_k_seed': (
        'DddFixedKSeedCoordinator',
        'DddFixedKSeedKind',
        'DddFixedKSeedResult',
        'DddFixedKSeedStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.iterative_solver': (
        'DddDelayedConflictSolver',
        'DddIterationRecord',
        'DddIterativeResult',
        'DddIterativeStatus',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.lifting': (
        'DddExactLiftResult',
        'DddExactLiftStatus',
        'DddExactSupportLifter',
        'DddRefinementReason',
        'build_ddd_cabin_path_core_cut',
        'build_ddd_prefix_conflict_cuts',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.local_resource_explainability': (
        'DddCpSatLocalCutCoverage',
        'DddCpSatLocalExplainabilityClass',
        'DddCpSatLocalExplainabilityObservation',
        'DddCpSatLocalExplainabilityReport',
        'DddCpSatLocalResourceAnalyzer',
        'DddCpSatLocalResourceProbe',
        'DddTimedFlowResourceWindow',
        'build_ddd_cp_sat_local_explainability_report',
        'ddd_timed_flow_core_support',
        'ddd_timed_flow_cover_excludes_support',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.models': (
        'DddFixedStart',
        'DddMovementCore',
        'DddMovementProblem',
        'DddMovementState',
        'DddResource',
        'DddResourceUsage',
        'DddRouteDecision',
        'DddRouteOption',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_problem': (
        'DddFixedTrajectoryStartDomain',
        'DddOptimizedInitialPlacementDomain',
        'DddReservoirBoundaryConfig',
        'DddReservoirBoundaryMode',
        'DddReservoirDispatchCardinalityMode',
        'DddReservoirTrajectoryKind',
        'DddReservoirTrajectoryStartDomain',
        'DddReservoirTrajectoryState',
        'DddTrajectoryFleetMode',
        'DddTrajectoryProblem',
        'DddTrajectoryStartDomain',
        'DddTrajectoryWaitingPolicy',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_branching': (
        'DddTrajectoryBranchCandidate',
        'DddTrajectoryBranchCandidateEvaluator',
        'DddTrajectoryBranchDecision',
        'DddTrajectoryBranchDomain',
        'DddTrajectoryBranchPredicate',
        'DddTrajectoryBranchPredicateKind',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_diving': (
        'DddTrajectoryDiveConfig',
        'DddTrajectoryDiveCoordinator',
        'DddTrajectoryDiveProgress',
        'DddTrajectoryDiveResult',
        'DddTrajectoryDiveStatus',
        'DddTrajectoryDiveStep',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_oip': (
        'DddOipTrajectoryStart',
        'build_ddd_oip_reference_trajectory',
        'build_ean_oip_trajectory',
        'build_ean_oip_plan_and_fleet',
        'ddd_oip_trajectories_from_ean_seed',
        'validate_ddd_oip_reference_trajectory',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_reservoir': (
        'DddReservoirFleetPlan',
        'build_ddd_reservoir_all_stop_seed',
        'build_ddd_reservoir_dispatch_anchors',
        'build_ddd_reservoir_neighbor_k_initial_pool',
        'build_ddd_reservoir_passenger_candidates',
        'build_ddd_reservoir_reference_trajectory',
        'build_ddd_stored_reservoir_trajectory',
        'build_ean_reservoir_movement_plan',
        'build_ean_reservoir_trajectory',
        'ddd_reservoir_covers_horizon',
        'validate_ddd_reservoir_reference_trajectory',
        'validate_ddd_reservoir_plan_against_artifact',
        'validate_ddd_reservoir_solution',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.network_refinement': (
        'DddNetworkTimeRefinementSolver',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.network_refinement_config': (
        'DddNetworkTimeRefinementConfig',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.network_refinement_model': (
        'DddNetworkTimeRefinementIteration',
        'DddNetworkTimeRefinementProgressCallback',
        'DddNetworkTimeRefinementProgressEvent',
        'DddNetworkTimeRefinementProgressStage',
        'DddNetworkTimeRefinementResult',
        'DddNetworkTimeRefinementStatus',
        'DddNetworkValidationResult',
        'DddNetworkValidationStatus',
        'DddTimeSplit',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.network_model': (
        'DddLayeredTimeArc',
        'DddLayeredTimeArcKind',
        'DddLayeredTimeNetwork',
        'DddLayeredTimeNetworkBuildStats',
        'DddLayeredTimeNode',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.network_time_space': (
        'DddAnonymousFlowDecomposer',
        'DddAnonymousFlowFixing',
        'DddAnonymousFlowMaster',
        'DddAnonymousFlowResult',
        'DddAnonymousFlowStatus',
        'DddAnonymousFlowValue',
        'DddAnonymousFlowWarmStart',
        'DddAnonymousFlowWarmStartProjector',
        'DddAnonymousMasterIncumbent',
        'DddAnonymousMasterProgress',
        'DddAnonymousPrefixFlowValue',
        'DddLayeredTimeNetworkBuilder',
        'DddNetworkPathProblemAdapter',
        'DddNetworkTimeObjective',
        'DddNetworkTimeProblem',
        'DddPrefixFormulationSize',
        'DddRecoveredScheduleFlowProjector',
        'build_ddd_cp_sat_timed_flow_support',
        'build_ddd_layer_state_earliest_arrival_ticks',
        'estimate_ddd_prefix_formulation_size',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.passenger_master': (
        'DddPassengerArcValue',
        'DddPassengerMasterModel',
        'DddPassengerMasterProblem',
        'DddPassengerMasterSolution',
        'DddPassengerServiceValue',
        'build_ddd_passenger_master_problem',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.primal_evaluation': (
        'DddEanPassengerPrimalEvaluator',
        'DddPrimalEvaluationResult',
        'DddPrimalEvaluationStatus',
        'DddPrimalEvaluationSummary',
        'DddPrimalEvaluator',
        'DddPrimalPoolEvaluationResult',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.reference': (
        'DddReferenceConflict',
        'DddReferenceHorizonCoverageError',
        'DddReferenceResourceConflictError',
        'DddReferenceResourceOccurrence',
        'DddReferenceResult',
        'DddReferenceSearchLimitError',
        'DddReferenceSearchMetrics',
        'DddReferenceSolution',
        'DddReferenceSolver',
        'DddReferenceStatus',
        'DddReferenceTrajectory',
        'DddReferenceTrajectoryGenerator',
        'DddReferenceVisit',
        'build_ddd_reference_visit',
        'ddd_reference_solution_from_recovered_schedules',
        'find_ddd_reference_conflicts',
        'validate_ddd_reference_solution',
        'validate_ddd_reference_trajectory',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.resource_time': (
        'DddAnonymousResourceRow',
        'DddAnonymousResourceRowKind',
        'DddAnonymousResourceRowTerm',
        'DddBoundedTickDelay',
        'DddResourceTimingAssumption',
        'DddResourceWindowCutMode',
        'DddResourceWindowSeparationResult',
        'DddTickInterval',
        'DddTimedResourceUsageWindow',
        'DddUniversalResourceConflict',
        'build_ddd_mandatory_resource_rows',
        'build_ddd_universal_resource_row',
        'ddd_feasible_source_interval',
        'find_ddd_universal_resource_conflict',
        'find_ddd_violated_interval_capacity_rows',
        'separate_ddd_resource_window_rows',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.support_master': (
        'DddSupportConflictCut',
        'DddSupportCost',
        'DddSupportLiteral',
        'DddSupportMaster',
        'DddSupportMasterResult',
        'DddSupportMasterStatus',
        'DddSupportObjective',
        'DddSupportSelection',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.time_refinement': (
        'DddCellFreeSupportRecovery',
        'DddEventCellInconsistency',
        'DddExactTimedEvent',
        'DddPrimalRecoveryResult',
        'DddPrimalRecoveryStatus',
        'DddRecoveredSchedule',
        'DddStrictTimeCellLifter',
        'DddStrictTimeLiftResult',
        'DddStrictTimeLiftStatus',
        'DddTimeRefinementIteration',
        'DddTimeRefinementResult',
        'DddTimeRefinementSolver',
        'DddTimeRefinementStalledError',
        'DddTimeRefinementStatus',
        'validate_ddd_recovered_schedule',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.time_space': (
        'DddPartialTimeMaster',
        'DddPartialTimeMasterResult',
        'DddPartialTimeMasterStatus',
        'DddPartialTimeProblem',
        'DddPartialTimedArc',
        'DddPartialTimedPath',
        'DddRouteOptionCost',
        'DddTerminalThresholdCost',
        'DddTimeBoundaryError',
        'DddTimeCell',
        'DddTimeDiscretization',
        'DddTimePartition',
        'DddTimeSpaceObjective',
        'ddd_normalize_time_seconds',
        'ddd_partial_arc_is_compatible',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.time_ticks': (
        'DDD_TIME_TICKS_PER_SECOND',
        'DDD_TIME_TICK_SECONDS',
        'DddTimeTick',
        'ddd_quantize_time_seconds',
        'ddd_seconds_to_tick',
        'ddd_tick_to_seconds',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.timed_flow_cover': (
        'DddCpSatTimedFlowSupport',
        'DddTimedArcFlowCount',
        'DddTimedFlowCoverCut',
        'DddTimedFlowRegion',
        'DddTimedFlowThresholdLiteral',
        'DddTimedFlowTimingScope',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_column_generation': (
        'DddTrajectoryBoundStatus',
        'DddTrajectoryOptimizerMode',
        'DddTrajectoryPricingCertificate',
        'DddTrajectoryReducedCost',
        'DddTrajectoryWaitingDomain',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_exact_pricing': (
        'DddTrajectoryExactNoWaitPricingOracle',
        'DddTrajectoryExactOipNoWaitPricingOracle',
        'DddTrajectoryExactReservoirNoWaitPricingOracle',
        'DddTrajectoryReservoirAnchorPricingOracle',
        'DddTrajectoryExactPricingResult',
        'DddTrajectoryExactPricingStatus',
        'DddTrajectoryExhaustivePricingOracle',
        'DddTrajectoryPricingFormulation',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_exhaustive_reference': (
        'DddExhaustiveTrajectoryLimitError',
        'DddExhaustiveTrajectoryMasterBuildResult',
        'DddExhaustiveTrajectoryMasterBuilder',
        'DddTrajectoryReferenceMasterBuildResult',
        'build_ddd_trajectory_reference_master',
        'ddd_trajectory_instance_fingerprint',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_passenger_lp': (
        'DddTrajectoryFactorizedLpOptimizer',
        'DddTrajectoryFactorizedMipReferenceOptimizer',
        'DddTrajectoryIntegratedLpReferenceOptimizer',
        'DddTrajectoryLoadPattern',
        'DddTrajectoryMasterDualMode',
        'DddTrajectoryPassengerDuals',
        'DddTrajectoryPassengerLpFormulation',
        'DddTrajectoryPassengerLpResult',
        'DddTrajectoryPassengerLpStatus',
        'DddTrajectoryPassengerMasterProblem',
        'DddTrajectoryPassengerMipResult',
        'DddTrajectoryPassengerOption',
        'DddTrajectoryPassengerRide',
        'enumerate_ddd_trajectory_load_patterns',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_pricing': (
        'DddTrajectoryHeuristicPricingSignal',
        'build_ddd_trajectory_heuristic_pricing_signal',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_coordinated_primal': (
        'DddTrajectoryCoordinatedPrimalGenerator',
        'DddTrajectoryCoordinatedPrimalResult',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_resource_windows': (
        'DddTrajectoryConflictRowMode',
        'DddTrajectoryResourceInterval',
        'DddTrajectoryResourceWindow',
        'DddTrajectoryResourceWindowIndex',
        'DddTrajectoryResourceWindowPricingTerm',
        'DddTrajectoryResourceWindowRow',
        'DddTrajectoryResourceWindowSeparationResult',
        'build_ddd_trajectory_resource_window_row',
        'build_ddd_trajectory_resource_window_rows',
        'ddd_trajectory_pair_has_resource_window_witness',
        'ddd_trajectory_resource_interval',
        'ddd_trajectory_resource_intervals',
        'enumerate_ddd_trajectory_resource_windows',
        'separate_ddd_trajectory_resource_windows',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_root_checkpoint': (
        'DDD_TRAJECTORY_ROOT_CHECKPOINT_SCHEMA_VERSION',
        'read_ddd_trajectory_root_cg_checkpoint',
        'write_ddd_trajectory_root_cg_checkpoint',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_root_column_generation': (
        'DddReservoirPrimalPricingMode',
        'DddTrajectoryDiversityMode',
        'DddTrajectoryExactRootColumnGenerationSolver',
        'DddTrajectoryRootCgIteration',
        'DddTrajectoryRootCgPricingDiagnostic',
        'DddTrajectoryRootCgResult',
        'DddTrajectoryRootCgState',
        'DddTrajectoryRootCgStatus',
        'ddd_trajectory_problem_instance_fingerprint',
        'build_ddd_all_stop_seed_trajectories',
    ),
    'ropeway_skip_stop_optimization.optimization.ddd.trajectory_slot': (
        'DddTrajectoryColumn',
        'DddTrajectoryColumnPool',
        'DddTrajectoryRestrictedMaster',
        'DddTrajectorySlotCandidate',
        'DddTrajectorySlotPoolOptimizer',
        'DddTrajectorySlotPoolResult',
        'DddTrajectorySlotPoolStatus',
        'build_ddd_trajectory_passenger_master_problem',
        'ddd_trajectory_column',
        'ddd_trajectory_column_signature',
    ),
}
_EXPORT_MODULE_BY_NAME = {
    name: module_name
    for module_name, names in _EXPORTS_BY_MODULE.items()
    for name in names
}

__all__ = [
    'DDD_TIME_TICKS_PER_SECOND',
    'DDD_TIME_TICK_SECONDS',
    'DddAggregateRouteCount',
    'DddAggregateRouteCountLiteral',
    'DddAggregateSupportCut',
    'DddAggregateSupportDistanceCut',
    'DddAnonymousResourceRow',
    'DddAnonymousResourceRowKind',
    'DddAnonymousResourceRowTerm',
    'DddCellFreeSupportRecovery',
    'DddCpSatPrimalOracle',
    'DddCpSatPrimalResult',
    'DddCpSatPrimalStatus',
    'DddCpSatLocalCutCoverage',
    'DddCpSatLocalExplainabilityClass',
    'DddCpSatLocalExplainabilityObservation',
    'DddCpSatLocalExplainabilityReport',
    'DddCpSatLocalResourceAnalyzer',
    'DddCpSatLocalResourceProbe',
    'DddCpSatFixedSupport',
    'DddCpSatTimedFlowSupport',
    'DddCpSatMasterCoupling',
    'DddCpSatPassengerObjectiveEvent',
    'DddCpSatPassengerRidePreference',
    'DddBoundedTickDelay',
    'DddAnonymousFlowDecomposer',
    'DddAnonymousFlowMaster',
    'DddAnonymousFlowFixing',
    'DddAnonymousMasterIncumbent',
    'DddAnonymousMasterProgress',
    'DddAnonymousFlowWarmStart',
    'DddAnonymousFlowWarmStartProjector',
    'DddRecoveredScheduleFlowProjector',
    'DddAnonymousPrefixFlowValue',
    'DddAnonymousFlowResult',
    'DddAnonymousFlowStatus',
    'DddPrefixFormulationSize',
    'DddAnonymousFlowValue',
    'DddDelayedConflictSolver',
    'DddEventCellInconsistency',
    'DddEanPassengerPrimalEvaluator',
    'DddPrimalPoolEvaluationResult',
    'DddExactLiftResult',
    'DddExactLiftStatus',
    'DddExactSupportLifter',
    'DddFixedKExperimentProfile',
    'DddArcFlowResourceClique',
    'DddArcFlowBoundaryInterval',
    'DddArcFlowResourceInterval',
    'DddArcFlowResourceRowMode',
    'DddBalancedReferenceStartBuilder',
    'DddBalancedReferenceStartResult',
    'DddCabinTimeExpandedArc',
    'DddCabinTimeExpandedNetwork',
    'DddCabinTimeExpandedNetworkBuilder',
    'DddFixedKArcFlowOptimizer',
    'DddFixedKArcFlowProgress',
    'DddFixedKArcFlowResult',
    'DddFixedKArcFlowSolveConfig',
    'DddFixedKArcFlowStatus',
    'DddFixedKOperatingMode',
    'DddFixedKProfileConfig',
    'DddFixedKStartPolicy',
    'DddFixedKBoundaryContext',
    'DddFixedKTrajectoryProblem',
    'DddFixedKSeedCoordinator',
    'DddFixedKSeedKind',
    'DddFixedKSeedResult',
    'DddFixedKSeedStatus',
    'DddExactTimedEvent',
    'DddFixedStart',
    'DddIterationRecord',
    'DddIterativeResult',
    'DddIterativeStatus',
    'DddMovementProblem',
    'DddMovementState',
    'DddLayeredTimeArc',
    'DddLayeredTimeArcKind',
    'DddLayeredTimeNetwork',
    'DddLayeredTimeNetworkBuildStats',
    'DddLayeredTimeNetworkBuilder',
    'DddLayeredTimeNode',
    'DddNetworkTimeObjective',
    'DddNetworkPathProblemAdapter',
    'DddNetworkTimeProblem',
    'build_ddd_layer_state_earliest_arrival_ticks',
    'estimate_ddd_prefix_formulation_size',
    'DddNetworkTimeRefinementIteration',
    'DddNetworkTimeRefinementProgressCallback',
    'DddNetworkTimeRefinementProgressEvent',
    'DddNetworkTimeRefinementProgressStage',
    'DddNetworkTimeRefinementResult',
    'DddNetworkTimeRefinementSolver',
    'DddNetworkTimeRefinementStatus',
    'DddNetworkValidationResult',
    'DddNetworkValidationStatus',
    'DddTimeSplit',
    'DddTimedFlowResourceWindow',
    'DddPartialTimedArc',
    'DddPartialTimedPath',
    'DddPassengerArcValue',
    'DddPassengerMasterModel',
    'DddPassengerMasterProblem',
    'DddPassengerMasterSolution',
    'DddPassengerServiceValue',
    'DddPartialTimeMaster',
    'DddPartialTimeMasterResult',
    'DddPartialTimeMasterStatus',
    'DddPartialTimeProblem',
    'DddPrimalRecoveryResult',
    'DddPrimalRecoveryStatus',
    'DddPrimalEvaluationResult',
    'DddPrimalEvaluationStatus',
    'DddPrimalEvaluationSummary',
    'DddPrimalEvaluator',
    'DddTrajectoryBoundStatus',
    'DddMovementCore',
    'DddFixedTrajectoryStartDomain',
    'DddOptimizedInitialPlacementDomain',
    'DddTrajectoryFleetMode',
    'DddTrajectoryProblem',
    'DddTrajectoryStartDomain',
    'DddOipTrajectoryStart',
    'build_ddd_oip_reference_trajectory',
    'build_ean_oip_trajectory',
    'build_ean_oip_plan_and_fleet',
    'ddd_oip_trajectories_from_ean_seed',
    'validate_ddd_oip_reference_trajectory',
    'DddTrajectoryColumn',
    'DddTrajectoryColumnPool',
    'DddExhaustiveTrajectoryLimitError',
    'DddExhaustiveTrajectoryMasterBuilder',
    'DddExhaustiveTrajectoryMasterBuildResult',
    'DddTrajectoryReferenceMasterBuildResult',
    'DddTrajectoryFactorizedLpOptimizer',
    'DddTrajectoryFactorizedMipReferenceOptimizer',
    'DddTrajectoryExactNoWaitPricingOracle',
    'DddTrajectoryExactOipNoWaitPricingOracle',
    'DddTrajectoryExactPricingResult',
    'DddTrajectoryExactPricingStatus',
    'DddTrajectoryExhaustivePricingOracle',
    'DddTrajectoryPricingFormulation',
    'DddTrajectoryExactRootColumnGenerationSolver',
    'DddTrajectoryDiversityMode',
    'DddTrajectoryConflictRowMode',
    'DddTrajectoryRootCgIteration',
    'DddTrajectoryRootCgPricingDiagnostic',
    'DddTrajectoryRootCgResult',
    'DddTrajectoryRootCgState',
    'DddTrajectoryRootCgStatus',
    'DDD_TRAJECTORY_ROOT_CHECKPOINT_SCHEMA_VERSION',
    'build_ddd_all_stop_seed_trajectories',
    'read_ddd_trajectory_root_cg_checkpoint',
    'write_ddd_trajectory_root_cg_checkpoint',
    'build_ddd_arc_flow_resource_cliques',
    'build_ddd_arc_flow_boundary_intervals',
    'DddTrajectoryIntegratedLpReferenceOptimizer',
    'DddTrajectoryHeuristicPricingSignal',
    'DddTrajectoryCoordinatedPrimalGenerator',
    'DddTrajectoryCoordinatedPrimalResult',
    'DddTrajectoryLoadPattern',
    'DddTrajectoryMasterDualMode',
    'DddTrajectoryOptimizerMode',
    'DddTrajectoryPassengerDuals',
    'DddTrajectoryPassengerLpFormulation',
    'DddTrajectoryPassengerLpResult',
    'DddTrajectoryPassengerLpStatus',
    'DddTrajectoryPassengerMasterProblem',
    'DddTrajectoryPassengerMipResult',
    'DddTrajectoryPassengerOption',
    'DddTrajectoryPassengerRide',
    'DddTrajectoryPricingCertificate',
    'DddTrajectoryReducedCost',
    'DddTrajectoryResourceInterval',
    'DddTrajectoryResourceWindow',
    'DddTrajectoryResourceWindowIndex',
    'DddTrajectoryResourceWindowPricingTerm',
    'DddTrajectoryResourceWindowRow',
    'DddTrajectoryResourceWindowSeparationResult',
    'DddTrajectoryRestrictedMaster',
    'DddTrajectorySlotCandidate',
    'DddTrajectorySlotPoolOptimizer',
    'DddTrajectorySlotPoolResult',
    'DddTrajectorySlotPoolStatus',
    'DddTrajectoryWaitingDomain',
    'DddRecoveredSchedule',
    'DddReferenceConflict',
    'DddReferenceHorizonCoverageError',
    'DddReferenceResult',
    'DddReferenceResourceConflictError',
    'DddReferenceResourceOccurrence',
    'DddReferenceSearchLimitError',
    'DddReferenceSearchMetrics',
    'DddReferenceSolution',
    'DddReferenceSolver',
    'DddReferenceStatus',
    'DddReferenceToEanMovementPlanAdapter',
    'DddReferenceTrajectory',
    'DddReferenceTrajectoryGenerator',
    'DddReferenceVisit',
    'DddRefinementReason',
    'DddResource',
    'DddResourceTimingAssumption',
    'DddResourceUsage',
    'DddRouteDecision',
    'DddRouteOption',
    'DddRouteOptionCost',
    'DddStrictTimeCellLifter',
    'DddStrictTimeLiftResult',
    'DddStrictTimeLiftStatus',
    'DddSupportConflictCut',
    'DddSupportCost',
    'DddSupportLiteral',
    'DddSupportMaster',
    'DddSupportMasterResult',
    'DddSupportMasterStatus',
    'DddSupportObjective',
    'DddSupportSelection',
    'DddTerminalThresholdCost',
    'DddTimeBoundaryError',
    'DddTimeCell',
    'DddTimeDiscretization',
    'DddTimePartition',
    'DddTimeRefinementIteration',
    'DddTimeRefinementResult',
    'DddTimeRefinementSolver',
    'DddTimeRefinementStatus',
    'DddTimeRefinementStalledError',
    'DddTimeSpaceObjective',
    'DddTimeTick',
    'DddTimedArcFlowCount',
    'DddTimedFlowCoverCut',
    'DddTimedFlowRegion',
    'DddTimedFlowThresholdLiteral',
    'DddTimedFlowTimingScope',
    'DddResourceWindowCutMode',
    'DddResourceWindowSeparationResult',
    'DddTickInterval',
    'DddTimedResourceUsageWindow',
    'DddUniversalResourceConflict',
    'EanArtifactToDddMovementProblemAdapter',
    'build_ddd_reference_visit',
    'ddd_reference_solution_from_recovered_schedules',
    'build_ddd_cabin_path_core_cut',
    'build_ddd_cp_sat_timed_flow_support',
    'build_ddd_cp_sat_local_explainability_report',
    'build_ddd_passenger_master_problem',
    'build_ddd_trajectory_passenger_master_problem',
    'build_ddd_trajectory_reference_master',
    'build_ddd_trajectory_resource_window_row',
    'build_ddd_trajectory_resource_window_rows',
    'build_ddd_trajectory_heuristic_pricing_signal',
    'build_ddd_mandatory_resource_rows',
    'build_ddd_universal_resource_row',
    'build_ddd_prefix_conflict_cuts',
    'ddd_normalize_time_seconds',
    'ddd_feasible_source_interval',
    'ddd_partial_arc_is_compatible',
    'ddd_quantize_time_seconds',
    'ddd_seconds_to_tick',
    'ddd_tick_to_seconds',
    'ddd_timed_flow_core_support',
    'ddd_timed_flow_cover_excludes_support',
    'find_ddd_reference_conflicts',
    'find_ddd_violated_interval_capacity_rows',
    'find_ddd_universal_resource_conflict',
    'separate_ddd_resource_window_rows',
    'validate_ddd_recovered_schedule',
    'validate_ddd_reference_solution',
    'validate_ddd_reference_trajectory',
    'ddd_trajectory_column',
    'ddd_trajectory_column_signature',
    'ddd_trajectory_instance_fingerprint',
    'ddd_trajectory_pair_has_resource_window_witness',
    'ddd_trajectory_resource_interval',
    'ddd_trajectory_resource_intervals',
    'enumerate_ddd_trajectory_load_patterns',
    'enumerate_ddd_trajectory_resource_windows',
    'separate_ddd_trajectory_resource_windows',
]


def __getattr__(name: str) -> Any:
    try:
        module_name = _EXPORT_MODULE_BY_NAME[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
