"""Lazy public facade for the event-activity network package."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS_BY_MODULE: dict[str, tuple[str, ...]] = {
    'ropeway_skip_stop_optimization.optimization.ean.artifact': (
        'EanBuildArtifact',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.baselines': (
        'EanMovementPlanBuilder',
        'EarliestAllStopEanMovementPlanBuilder',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.build_profile': (
        'EanArtifactBuildMetrics',
        'EanBuildProgressCallback',
        'EanBuildProgressEvent',
        'EanBuildProgressKind',
        'EanBuildStage',
        'EanMovementBuildMetrics',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.builders': (
        'AllPairsHeadwayPairBuilder',
        'CanonicalFixedKRopeCabinStartBuilder',
        'ContinuousAllStopMaxCabinStartBuilder',
        'CyclicPatternVisitBuilder',
        'DeterministicPhysicalNodeToSwitchStartBuilder',
        'EanArtifactConstructionMode',
        'EanBuildArtifactBuilder',
        'EanCabinStartBuilder',
        'EanCompatibilityArtifactAssembler',
        'EanPassengerCandidateBuildResult',
        'EanPassengerCandidateBuilder',
        'EvenlySpacedAllStopCabinStartBuilder',
        'EanCanonicalRopeStartSlot',
        'HeadwayCandidateBuilder',
        'HeadwayCheckpointBuilder',
        'HeadwayDurationBuilder',
        'HeadwayDurations',
        'HeadwayPairBuilder',
        'NetworkEanBuildArtifactBuilder',
        'NetworkSkipStopTimingBuilder',
        'NetworkVisitBuilder',
        'OperatingSpeedHeadwayDurationBuilder',
        'PhysicalMovementNetworkBuilder',
        'ResolvedEanArtifactInputs',
        'SkipStopHeadwayCheckpointBuilder',
        'SparseHeadwayPairBuilder',
        'SwitchVisitBuilder',
        'SwitchVisitHeadwayCandidateBuilder',
        'activation_reference_for_checkpoint_kind',
        'build_cyclic_switch_transitions',
        'build_ean_ride_candidates',
        'calculate_min_max_state_to_next_seconds',
        'count_visits_by_cabin',
        'expand_demands_to_ean_groups',
        'network_ean_builder_for_pattern',
        'release_seconds_for_demand',
        'time_reference_for_checkpoint_kind',
        'transition_by_from_switch_id',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.capacity_preparation': (
        'EanPreparedRing',
        'EanPreparedRingBuilder',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.fleet': (
        'EanFleetPlan',
        'EanInitialPlacementParameters',
        'EanInitialPlacementState',
        'EanInitialPlacementStateKind',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.formulation_config': (
        'ALL_EAN_FORMULATION_SELECTION_NAMES',
        'EanBoardTimeFormulation',
        'EanFormulationConfig',
        'EanHorizonFormulation',
        'EanSlotActivationFormulation',
        'EanStopSkipTimingFormulation',
        'EanTimeBoundFormulation',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.headway_classification': (
        'EanFixedStartHeadwayClassifier',
        'EanHeadwayCandidateTimeBounds',
        'EanHeadwayPairClassification',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.headway_merge_relaxation': (
        'EanDirectMergeHeadwayRelaxationIndex',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.headway_order_families': (
        'EanHeadwayOrderFamilyIndex',
        'EanHeadwayOrderReference',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.models': (
        'EanActivationReference',
        'EanCabinStart',
        'EanCabinStartKind',
        'EanConfig',
        'EanDemandGroup',
        'EanFleetCardinalityMode',
        'EanFleetConfig',
        'EanFleetMode',
        'EanHeadwayPairScope',
        'EanRideCandidate',
        'EanTimeReference',
        'HeadwayCandidate',
        'HeadwayCheckpointDefinition',
        'HeadwayCheckpointKind',
        'HeadwayPair',
        'Passenger',
        'RideCandidate',
        'SkipStopTiming',
        'StationEanConfig',
        'StationWaitingMode',
        'SwitchTransition',
        'SwitchVisitBuildResult',
        'SwitchVisitDefinition',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.network': (
        'EanCirculationPattern',
        'EanCirculationPatternDefinition',
        'EanMovementEffect',
        'EanMovementNetwork',
        'EanMovementState',
        'EanPassengerBehavior',
        'EanResource',
        'EanResourceConflictIndex',
        'EanResourceKind',
        'EanResourceUsage',
        'EanRouteOption',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.optimization_config': (
        'ALL_EAN_OPTIMIZATION_NAMES',
        'ALL_EAN_SELECTION_NAMES',
        'EanOptimizationConfig',
        'EanOptimizationName',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.optimizers': (
        'EanDelayedHeadwayProbeStrategy',
        'EanEagerHeadwayProbeStrategy',
        'EanFixedMovementPassengerModel',
        'EanFixedMovementPassengerModelBuilder',
        'EanFixedMovementPassengerProblem',
        'EanFleetSymmetryBreaker',
        'EanHeadwayProbeContext',
        'EanHeadwayProbeStrategy',
        'EanInitialPlacementCapacityCertificate',
        'EanInitialPlacementCapacityOptimizer',
        'EanInitialPlacementCapacityOutputMode',
        'EanInitialPlacementCapacityProbeResult',
        'EanInitialPlacementCapacityProblem',
        'EanInitialPlacementCapacityResult',
        'EanInitialPlacementCapacitySearchConfig',
        'EanInitialPlacementCapacitySolveConfig',
        'EanInitialPlacementDelayedHeadwayConfig',
        'EanInitialPlacementFeasibilityOptimizer',
        'EanInitialPlacementFeasibilityProblem',
        'EanInitialPlacementFeasibilityStatus',
        'EanInitialPlacementHeadwayGenerationMode',
        'EanInitialPlacementHeadwayGenerationRound',
        'EanInitialPlacementMipStart',
        'EanInitialPlacementMipStartSource',
        'EanMipStartStrategy',
        'EanModelBuildMetrics',
        'EanMovementFeasibilityProblem',
        'EanNoPeriodicRouteCertificateError',
        'EanOptimizationMetadata',
        'EanOptimizationProblemKind',
        'EanOptimizationResult',
        'EanOptimizer',
        'EanPassengerAssignment',
        'EanPassengerAssignmentDomain',
        'EanPassengerObjective',
        'EanPassengerServiceProblem',
        'EanPeriodicRouteCapacityBound',
        'EanPeriodicRouteCapacityBoundBuilder',
        'EanPeriodicRouteLeg',
        'EanPeriodicRouteMipStartSeedBuilder',
        'EanSolveConfig',
        'GurobiCheckpointConfig',
        'GurobiSolverPolicy',
        'GurobiSolverPolicyPreset',
        'apply_gurobi_solver_policy',
        'gurobi_solver_policy_for_preset',
        'solver_integer_upper_bound',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.packing_capacity': (
        'EanFleetPackingRegion',
        'EanFleetPackingRegionKind',
        'EanInitialPlacementPackingBound',
        'EanInitialPlacementPackingBoundBuilder',
        'segment_packing_capacity',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.passenger_objective': (
        'EanPassengerObjectiveDefinition',
        'EanPassengerObjectiveEvent',
        'ean_passenger_objective_definition',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.passenger_plan': (
        'EanPassengerServicePlan',
        'EanServedRideGroup',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.plan': (
        'EanCabinTrajectory',
        'EanCabinVisit',
        'EanMovementPlan',
        'EanRouteDecision',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.primal_seed': (
        'EanPrimalSeed',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.projection': (
        'EanPhysicalEvent',
        'EanPhysicalEventKind',
        'EanPhysicalReplay',
        'project_ean_movement_plan_to_physical_replay',
    ),
    'ropeway_skip_stop_optimization.optimization.ean.validation': (
        'validate_ean_initial_boundary_against_artifact',
        'validate_ean_movement_plan_against_artifact',
    ),
}
_EXPORT_MODULE_BY_NAME = {
    name: module_name
    for module_name, names in _EXPORTS_BY_MODULE.items()
    for name in names
}

__all__ = [
    'AllPairsHeadwayPairBuilder',
    'CanonicalFixedKRopeCabinStartBuilder',
    'SparseHeadwayPairBuilder',
    'ALL_EAN_OPTIMIZATION_NAMES',
    'ALL_EAN_FORMULATION_SELECTION_NAMES',
    'ALL_EAN_SELECTION_NAMES',
    'ContinuousAllStopMaxCabinStartBuilder',
    'CyclicPatternVisitBuilder',
    'DeterministicPhysicalNodeToSwitchStartBuilder',
    'EarliestAllStopEanMovementPlanBuilder',
    'EanActivationReference',
    'EanBuildArtifact',
    'EanBuildArtifactBuilder',
    'EanCompatibilityArtifactAssembler',
    'EanArtifactConstructionMode',
    'EanCirculationPattern',
    'EanCirculationPatternDefinition',
    'EanArtifactBuildMetrics',
    'EanBuildProgressCallback',
    'EanBuildProgressEvent',
    'EanBuildProgressKind',
    'EanBuildStage',
    'EanMovementBuildMetrics',
    'EanBoardTimeFormulation',
    'EanCabinStartBuilder',
    'EanCabinStart',
    'EanCabinStartKind',
    'EvenlySpacedAllStopCabinStartBuilder',
    'EanCanonicalRopeStartSlot',
    'EanCabinTrajectory',
    'EanCabinVisit',
    'EanConfig',
    'EanDemandGroup',
    'EanFleetConfig',
    'EanFleetCardinalityMode',
    'EanFleetPackingRegion',
    'EanFleetPackingRegionKind',
    'EanFleetMode',
    'EanHeadwayPairScope',
    'EanFleetPlan',
    'EanFleetSymmetryBreaker',
    'EanFixedStartHeadwayClassifier',
    'EanHeadwayCandidateTimeBounds',
    'EanHeadwayPairClassification',
    'EanHeadwayOrderFamilyIndex',
    'EanHeadwayOrderReference',
    'EanDirectMergeHeadwayRelaxationIndex',
    'EanInitialPlacementParameters',
    'EanInitialPlacementCapacityCertificate',
    'EanInitialPlacementCapacityOutputMode',
    'EanInitialPlacementCapacityProbeResult',
    'EanInitialPlacementCapacityOptimizer',
    'EanInitialPlacementCapacityProblem',
    'EanInitialPlacementCapacityResult',
    'EanInitialPlacementCapacitySolveConfig',
    'EanInitialPlacementCapacitySearchConfig',
    'EanInitialPlacementDelayedHeadwayConfig',
    'EanInitialPlacementHeadwayGenerationMode',
    'EanInitialPlacementHeadwayGenerationRound',
    'EanInitialPlacementFeasibilityOptimizer',
    'EanInitialPlacementFeasibilityProblem',
    'EanInitialPlacementFeasibilityStatus',
    'EanInitialPlacementMipStart',
    'EanInitialPlacementMipStartSource',
    'EanHeadwayProbeStrategy',
    'EanHeadwayProbeContext',
    'EanEagerHeadwayProbeStrategy',
    'EanDelayedHeadwayProbeStrategy',
    'EanPeriodicRouteCapacityBound',
    'EanPeriodicRouteCapacityBoundBuilder',
    'EanNoPeriodicRouteCertificateError',
    'EanPeriodicRouteLeg',
    'EanPeriodicRouteMipStartSeedBuilder',
    'EanInitialPlacementPackingBound',
    'EanInitialPlacementPackingBoundBuilder',
    'EanInitialPlacementState',
    'EanInitialPlacementStateKind',
    'EanFormulationConfig',
    'EanFixedMovementPassengerModel',
    'EanFixedMovementPassengerModelBuilder',
    'EanFixedMovementPassengerProblem',
    'EanHorizonFormulation',
    'EanSlotActivationFormulation',
    'EanMovementPlan',
    'EanMovementPlanBuilder',
    'EanMipStartStrategy',
    'EanOptimizationConfig',
    'EanOptimizationName',
    'EanPassengerCandidateBuilder',
    'EanPassengerCandidateBuildResult',
    'EanMovementFeasibilityProblem',
    'EanMovementEffect',
    'EanMovementNetwork',
    'EanMovementState',
    'EanModelBuildMetrics',
    'EanOptimizationMetadata',
    'EanOptimizationProblemKind',
    'EanOptimizationResult',
    'EanOptimizer',
    'EanPassengerObjective',
    'EanPassengerObjectiveDefinition',
    'EanPassengerObjectiveEvent',
    'EanPassengerBehavior',
    'EanPassengerAssignment',
    'EanPassengerAssignmentDomain',
    'EanPassengerServicePlan',
    'EanPassengerServiceProblem',
    'ean_passenger_objective_definition',
    'EanPreparedRing',
    'EanPreparedRingBuilder',
    'EanPrimalSeed',
    'EanPhysicalEvent',
    'EanPhysicalEventKind',
    'EanPhysicalReplay',
    'EanRideCandidate',
    'EanResource',
    'EanResourceConflictIndex',
    'EanResourceKind',
    'EanResourceUsage',
    'EanRouteOption',
    'EanRouteDecision',
    'EanServedRideGroup',
    'EanSolveConfig',
    'EanStopSkipTimingFormulation',
    'EanTimeReference',
    'EanTimeBoundFormulation',
    'GurobiSolverPolicy',
    'GurobiSolverPolicyPreset',
    'GurobiCheckpointConfig',
    'HeadwayCandidateBuilder',
    'HeadwayCandidate',
    'HeadwayCheckpointDefinition',
    'HeadwayCheckpointBuilder',
    'HeadwayCheckpointKind',
    'HeadwayDurationBuilder',
    'HeadwayDurations',
    'HeadwayPair',
    'HeadwayPairBuilder',
    'OperatingSpeedHeadwayDurationBuilder',
    'NetworkEanBuildArtifactBuilder',
    'NetworkSkipStopTimingBuilder',
    'NetworkVisitBuilder',
    'network_ean_builder_for_pattern',
    'PhysicalMovementNetworkBuilder',
    'Passenger',
    'ResolvedEanArtifactInputs',
    'RideCandidate',
    'SkipStopTiming',
    'SkipStopHeadwayCheckpointBuilder',
    'StationEanConfig',
    'StationWaitingMode',
    'SwitchVisitBuilder',
    'SwitchVisitHeadwayCandidateBuilder',
    'SwitchTransition',
    'SwitchVisitBuildResult',
    'SwitchVisitDefinition',
    'activation_reference_for_checkpoint_kind',
    'apply_gurobi_solver_policy',
    'build_ean_ride_candidates',
    'build_cyclic_switch_transitions',
    'calculate_min_max_state_to_next_seconds',
    'count_visits_by_cabin',
    'expand_demands_to_ean_groups',
    'gurobi_solver_policy_for_preset',
    'time_reference_for_checkpoint_kind',
    'transition_by_from_switch_id',
    'release_seconds_for_demand',
    'segment_packing_capacity',
    'solver_integer_upper_bound',
    'project_ean_movement_plan_to_physical_replay',
    'validate_ean_initial_boundary_against_artifact',
    'validate_ean_movement_plan_against_artifact',
]


def __getattr__(name: str) -> Any:
    try:
        module_name = _EXPORT_MODULE_BY_NAME[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
